<?php

namespace GAlter\GestionBundle\Entity\Demo;

use Doctrine\ORM\EntityRepository;

/**
 * roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roleRepository extends EntityRepository
{
}
