g_alter_gestion:
    resource: "@GAlterGestionBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation


user_one_registration:
    pattern:  /enregistrement/etudiant
    defaults: { _controller: GAlterUserBundle:RegistrationUserOne:register }

user_two_registration:
    pattern:  /enregistrement/tuteur
    defaults: { _controller: GAlterUserBundle:RegistrationUserTwo:register }

user_four_registration:
    pattern:  /enregistrement/tuteur_entreprise
    defaults: { _controller: GAlterUserBundle:RegistrationUserFour:register }

user_three_registration:
    pattern:  /enregistrement/responsable
    defaults: { _controller: GAlterUserBundle:RegistrationUserThree:register }

fos_user_registration_confirmed:
    pattern:  /register/confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_registration_confirm:
    pattern:  /register/confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm}
    requirements:
        _method: GET

fos_user_registration_check_email:
    pattern:  /register/check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail}
    requirements:
        _method: GET



fos_user_security_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }


fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        _method: GET


fos_user_profile_edit:
    pattern:  /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }
    requirements:
        _methods: GET POST

fos_user_resetting_request:
    pattern:  /resetting/request
    defaults: { _controller: FOSUserBundle:Resetting:request }
    requirements:
        _method: GET

fos_user_resetting_send_email:
    pattern:  /resetting/send-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }


fos_user_resetting_check_email:
    pattern:  /resetting/check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements:
        _method: GET


fos_user_resetting_reset:
    pattern:  /resetting/reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    requirements:
        _methods: GET POST



fos_user_change_password:
    pattern:  /profile/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements:
        _methods: GET POST



fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /optional_routing_prefix




g_alter_user_user:
    resource: "@GAlterUserBundle/Resources/config/routing/user.yml"
    prefix:   /user



g_alter_gestion_formation:
    resource: "@GAlterGestionBundle/Resources/config/routing/formation.yml"
    prefix:   /formation

g_alter_user_etudiant:
    resource: "@GAlterUserBundle/Resources/config/routing/etudiant.yml"
    prefix:   /etudiant


g_alter_gestion_remarquetuteurrapport:
    resource: "@GAlterGestionBundle/Resources/config/routing/remarquetuteurrapport.yml"
    prefix:   /remarquetuteurrapport


g_alter_gestion_anneeformationetudiant:
    resource: "@GAlterGestionBundle/Resources/config/routing/anneeformationetudiant.yml"
    prefix:   /anneeformationetudiant



g_alter_gestion_document:
    resource: "@GAlterGestionBundle/Resources/config/routing/document.yml"
    prefix:   /document