<?php

namespace GAlter\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * options_compteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionscompteRepository extends EntityRepository
{
}
