<?php

namespace GAlter\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * remarque_responsable_rapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Remarque_responsable_rapportRepository extends EntityRepository
{
}
