<?php

namespace GAlter\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
}
