<?php

namespace GAlter\UserBundle\Entity;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * retourne les etudiantassocié a une formation
     *
     */

    public function getStudentByIdFormation($formation){
        $query_builder=$this->createQueryBuilder('e');
        $query_builder->join('e.anneeFormationEtudiant', 'a')
            ->where('a.formation = :formation')
            ->setParameter('formation', $formation);
        return $query_builder;

    }


    public function getAnneeFormation($formation){
        $query_builder=$this->createQueryBuilder('e');
        $query_builder->join('e.anneeFormationEtudiant', 'a')
            ->where('a.formation = :formation')
            ->setParameter('formation', $formation);
        return $query_builder;

    }


}
