<?php

namespace GAlter\UserBundle\Entity;

/**
 * TuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
