anneeformationetudiant:
    path:     /
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:index" }

anneeformationetudiant_show:
    path:     /{id}/show
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:show" }

anneeformationetudiant_new:
    path:     /new
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:new" }

anneeformationetudiant_create:
    path:     /create
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:create" }
    methods:  POST

anneeformationetudiant_edit:
    path:     /{id}/edit
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:edit" }

anneeformationetudiant_update:
    path:     /{id}/update
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:update" }
    methods:  [POST, PUT]

anneeformationetudiant_delete:
    path:     /{id}/delete
    defaults: { _controller: "GAlterGestionBundle:AnneeFormationEtudiant:delete" }
    methods:  [POST, DELETE]
