<?php

namespace Acme\DemoBundle\Entity\Demo;

use Doctrine\ORM\EntityRepository;

/**
 * etudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etudiantRepository extends EntityRepository
{
}
