etudiant:
    path:     /
    defaults: { _controller: "GAlterUserBundle:etudiant:index" }

etudiant_show:
    path:     /{id}/show
    defaults: { _controller: "GAlterUserBundle:etudiant:show" }

etudiant_new:
    path:     /new
    defaults: { _controller: "GAlterUserBundle:etudiant:new" }

etudiant_create:
    path:     /create
    defaults: { _controller: "GAlterUserBundle:etudiant:create" }
    methods:  POST

etudiant_edit:
    path:     /{id}/edit
    defaults: { _controller: "GAlterUserBundle:etudiant:edit" }

etudiant_update:
    path:     /{id}/update
    defaults: { _controller: "GAlterUserBundle:etudiant:update" }
    methods:  [POST, PUT]

etudiant_delete:
    path:     /{id}/delete
    defaults: { _controller: "GAlterUserBundle:etudiant:delete" }
    methods:  [POST, DELETE]
